name: Daily Event Wisher

on:
  schedule:
    - cron: '28 19 * * *'
    
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode?'
        required: false
        default: 'false'
      test_email:
        description: 'Test email address (optional)'
        required: false
        default: ''
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Restore Google Service Account JSON
        run: |
            echo "${{secrets.GOOGLE_SERVICE_KEY }}" | base64 --decode > service_account.json

      - name: Run the script with logging
        run: |
          source .venv/bin/activate
          python main.py
